[workspace]
members = ["server", "wire_protocol"]
resolver = "2"

[workspace.dependencies]
rmp-serde = "1.1.2"
serde = { version = "1.0.196", features = ["derive"] }
uuid = { version = "1.7.0", features = ["fast-rng", "serde", "v4"] }
