receivers:
  otlp:
    protocols:
      grpc:

  hostmetrics:
    scrapers:
      cpu:
      load:
      memory:
      network:

exporters:
  debug:

  prometheusremotewrite:
    endpoint: prometheus:9411/api/prom/push
    tls:
      insecure: true

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      # TODO NOW REMOVE DEBUG
      exporters: [prometheusremotewrite, debug]