[package]
name = "matchmaker-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
console-subscriber = { version = "0.2.0", features = ["parking_lot"] }
redis = "0.24.0"
rmp-serde = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { workspace = true }
wire_protocol = { path = "../wire_protocol" }

[profile.dev.package.backtrace]
opt-level = 3
