[package]
name = "load_tester_client"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
rand = "0.8.5"
rand_distr = "0.4.3"
