name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone the repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push matchmaker Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: deployment/docker/matchmaker-rs.Dockerfile
          push: true
          tags: brandonpollack23/matchmaker-rs:latest
      - name: Build and push test client Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: deployment/docker/load_tester_client.Dockerfile
          push: true
          tags: brandonpollack23/matchmaker-load-test-client:latest
